### PR TITLE
patchset: add ffmpeg-vaapi hevc scc encode support

### PR DESCRIPTION
**Pull request by feiwan1**
Signed-off-by: Fei Wang <fei.w.wang@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
FYI, current CI pre-check is broken due to https://github.com/intel/media-driver/issues/1067

**Comment by feiwan1** [comment]
> FYI, current CI pre-check is broken due to [intel/media-driver#1067](https://github.com/intel/media-driver/issues/1067)

OK, get it. Thanks for your information.

**Comment by uartie** [comment]
> > FYI, current CI pre-check is broken due to [intel/media-driver#1067](https://github.com/intel/media-driver/issues/1067)
> 
> OK, get it. Thanks for your information.

CI pre-check is fixed

**Comment by uartie** [comment]
Seems this can't pass fate tests

**Pull request merged**
