### PR TITLE
patchset 0088-0089: add max_frame_size and dblk_idc

### PR DESCRIPTION
**Pull request by wenbinc-Bin**
patch 0088: add max_frame_size support.
patch 0089: add DisableDeblockIdc (dblk_idc).

### CODE REVIEW

**Comment by wenbinc-Bin** [comment]
@feiwan1. I add two args support and pass the precheck. Could you please help me to merge it.

**Comment by feiwan1** [comment]
All test pass, merge the patch. thanks.

**Comment by feiwan1** [comment]
@wenbinc-Bin , did you submit your patch to ffmpeg community?

**Comment by wenbinc-Bin** [comment]
> @wenbinc-Bin , did you submit your patch to ffmpeg community?

Yes, I have submitted these two patches to ffmpeg community.

**Pull request merged**
