### PR TITLE
patchset: add skip_frame invalid to skip invalid nalus to avoid gpu hang

### PR DESCRIPTION
**Pull request by zongwave**

### CODE REVIEW

**Comment by uartie** [comment]
this breaks fate tests... please resolve

**Comment by zongwave** [comment]
verified this patch with fate test locally. the fate test failure was caused by patchset/0001

**Comment by uartie** [comment]
> verified this patch with fate test locally. the fate test failure was caused by patchset/0001

Thanks.  This should be fixed with #58.  Please rebase.

**Comment by feiwan1** [comment]
All test passed, merge this patch.

**Pull request merged**
