### PR TITLE
Add features to ffmpeg-qsv. Fix the problem about device memory usage.

### PR DESCRIPTION
**Pull request by wenbinc-Bin**

### CODE REVIEW

**Comment by uartie** [comment]
Have these changes been contributed/submitted to upstream ML, yet?

**Comment by uartie** [comment]
I can't find upstream submission.  We should not accept patches into cartwheel unless they are already submitted upstream and under review.

**Comment by wenbinc-Bin** [comment]
Ok, I will submit them to ffmpeg community, and then submit to cartwheel again.

**Comment by uartie** [comment]
Thanks @wenbinc-Bin.  When you resubmit, you should use the new https://github.com/intel-media-ci/cartwheel-ffmpeg repo as this repo will be deprecated in the next day or two.

**Comment by wenbinc-Bin** [comment]
Ok, thanks @uartie .

**Pull request closed without merging**
